// UI label transliterations — phonetic (same word in target script), NOT meaning-based translation

const LABELS = {
  'en': {
    home: 'Home', translation: 'Translation', nativeToEnglish: 'Native to English',
    continuousListening: 'Continuous Listening', englishToNative: 'English to Native',
    visionTranslate: 'Vision Translate', library: 'Library', history: 'History',
    profile: 'Profile', settings: 'Settings', logout: 'Logout',
    settingsTitle: 'Settings', managePreferences: 'Manage your preferences',
    profileTitle: 'Profile', accountPreferences: 'Account & Preferences',
    defaultLanguage: 'Default Language', translate: 'Translate', translating: 'Translating…',
    transcriptHistory: 'Transcript History', noHistory: 'No history yet',
    savedRewrites: 'Saved Rewrites',
    totalTranscripts: 'Total Transcripts', avgConfidence: 'Avg Confidence',
    apiCalls: 'API Calls', languageUsage: 'Language Usage',
    confidenceTrend: 'Confidence Trend', dailyActivity: 'Daily Activity',
    thisWeek: 'This Week', connectedChannels: 'Connected Channels',
    supportedLanguages: 'Supported Languages', visionTranslateTitle: 'Vision Translate',
    dropImageHere: 'Drop image here', newImage: 'New Image',
    typeEnglishHere: 'Type English here…', translationAppears: 'Translation appears here',
    translationsNative: 'Translation (Native)', textTranslate: 'Text Translate',
    original: 'Original', copyAll: 'Copy All', download: 'Download',
    noResults: 'No results', starred: 'Starred',
    nativeToEnglishDesc: 'Speak in your language, get English',
    continuousListeningDesc: 'Hands-free with silence detection',
    englishToNativeDesc: 'Type English, get native translation',
    visionTranslateDesc: 'Translate text from images',
    chooseMode: 'Choose a mode to get started',
    termsPreserved: 'Terms preserved',
    pressStartListening: 'Press Start Listening to begin',
    shortcuts: 'Shortcuts',
    multiLangOutput: 'Multi-language output',
    rewriteTone: 'Rewrite tone',
    dropAudioHere: 'Drop audio file here',
    aiTools: 'AI Tools',
    transcript: 'Transcript',
    speechToText: 'Speech to Text',
    uploadAudio: 'Upload Audio',
    transcribingAudio: 'Transcribing audio…',
    startListening: 'Start Listening',
    stopListening: 'Stop Listening',
  },

  'hi-IN': {
    home: 'होम', translation: 'ट्रांसलेशन', nativeToEnglish: 'नेटिव टू इंग्लिश',
    continuousListening: 'कंटीन्यूअस लिसनिंग', englishToNative: 'इंग्लिश टू नेटिव',
    visionTranslate: 'विज़न ट्रांसलेट', library: 'लाइब्रेरी', history: 'हिस्ट्री',
    profile: 'प्रोफाइल', settings: 'सेटिंग्स', logout: 'लॉगआउट',
    settingsTitle: 'सेटिंग्स', managePreferences: 'अपनी प्रेफरेंसेज़ मैनेज करें',
    profileTitle: 'प्रोफाइल', accountPreferences: 'अकाउंट & प्रेफरेंसेज़',
    defaultLanguage: 'डिफ़ॉल्ट लैंग्वेज', translate: 'ट्रांसलेट', translating: 'ट्रांसलेटिंग…',
    transcriptHistory: 'ट्रांसक्रिप्ट हिस्ट्री', noHistory: 'कोई हिस्ट्री नहीं',
    savedRewrites: 'सेव्ड रिराइट्स',
    totalTranscripts: 'टोटल ट्रांसक्रिप्ट्स', avgConfidence: 'एवरेज कॉन्फिडेंस',
    apiCalls: 'API कॉल्स', languageUsage: 'लैंग्वेज यूसेज',
    confidenceTrend: 'कॉन्फिडेंस ट्रेंड', dailyActivity: 'डेली एक्टिविटी',
    thisWeek: 'दिस वीक', connectedChannels: 'कनेक्टेड चैनल्स',
    supportedLanguages: 'सपोर्टेड लैंग्वेजेज़', visionTranslateTitle: 'विज़न ट्रांसलेट',
    dropImageHere: 'इमेज ड्रॉप करें', newImage: 'न्यू इमेज',
    typeEnglishHere: 'यहाँ इंग्लिश टाइप करें…', translationAppears: 'ट्रांसलेशन यहाँ दिखेगा',
    translationsNative: 'ट्रांसलेशन (नेटिव)', textTranslate: 'टेक्स्ट ट्रांसलेट',
    original: 'ओरिजिनल', copyAll: 'कॉपी ऑल', download: 'डाउनलोड',
    noResults: 'कोई रिज़ल्ट नहीं', starred: 'स्टार्ड',
    nativeToEnglishDesc: 'अपनी भाषा में बोलें, इंग्लिश पाएं',
    continuousListeningDesc: 'हैंड्स-फ्री विद साइलेंस डिटेक्शन',
    englishToNativeDesc: 'इंग्लिश टाइप करें, नेटिव ट्रांसलेशन पाएं',
    visionTranslateDesc: 'इमेज से टेक्स्ट ट्रांसलेट करें',
    chooseMode: 'शुरू करने के लिए मोड चुनें',
    termsPreserved: 'टर्म्स प्रिज़र्व्ड',
    pressStartListening: 'स्टार्ट लिसनिंग प्रेस करें',
    shortcuts: 'शॉर्टकट्स',
    multiLangOutput: 'मल्टी-लैंग्वेज आउटपुट',
    rewriteTone: 'रिराइट टोन',
    dropAudioHere: 'ऑडियो फाइल ड्रॉप करें',
    aiTools: 'AI टूल्स',
    transcript: 'ट्रांसक्रिप्ट',
    speechToText: 'स्पीच टू टेक्स्ट',
    uploadAudio: 'अपलोड ऑडियो',
    transcribingAudio: 'ट्रांसक्राइबिंग ऑडियो…',
    startListening: 'स्टार्ट लिसनिंग',
    stopListening: 'स्टॉप लिसनिंग',
  },

  'kn-IN': {
    home: 'ಹೋಮ್', translation: 'ಟ್ರಾನ್ಸ್‌ಲೇಶನ್', nativeToEnglish: 'ನೇಟಿವ್ ಟು ಇಂಗ್ಲಿಷ್',
    continuousListening: 'ಕಂಟಿನ್ಯೂಅಸ್ ಲಿಸನಿಂಗ್', englishToNative: 'ಇಂಗ್ಲಿಷ್ ಟು ನೇಟಿವ್',
    visionTranslate: 'ವಿಷನ್ ಟ್ರಾನ್ಸ್‌ಲೇಟ್', library: 'ಲೈಬ್ರರಿ', history: 'ಹಿಸ್ಟರಿ',
    profile: 'ಪ್ರೊಫೈಲ್', settings: 'ಸೆಟ್ಟಿಂಗ್ಸ್', logout: 'ಲಾಗ್‌ಔಟ್',
    settingsTitle: 'ಸೆಟ್ಟಿಂಗ್ಸ್', managePreferences: 'ನಿಮ್ಮ ಪ್ರೆಫರೆನ್ಸಸ್ ಮ್ಯಾನೇಜ್ ಮಾಡಿ',
    profileTitle: 'ಪ್ರೊಫೈಲ್', accountPreferences: 'ಅಕೌಂಟ್ & ಪ್ರೆಫರೆನ್ಸಸ್',
    defaultLanguage: 'ಡಿಫಾಲ್ಟ್ ಲ್ಯಾಂಗ್ವೇಜ್', translate: 'ಟ್ರಾನ್ಸ್‌ಲೇಟ್', translating: 'ಟ್ರಾನ್ಸ್‌ಲೇಟಿಂಗ್…',
    transcriptHistory: 'ಟ್ರಾನ್ಸ್‌ಕ್ರಿಪ್ಟ್ ಹಿಸ್ಟರಿ', noHistory: 'ಹಿಸ್ಟರಿ ಇಲ್ಲ',
    savedRewrites: 'ಸೇವ್ಡ್ ರಿರೈಟ್ಸ್',
    totalTranscripts: 'ಟೋಟಲ್ ಟ್ರಾನ್ಸ್‌ಕ್ರಿಪ್ಟ್ಸ್', avgConfidence: 'ಆವರೇಜ್ ಕಾನ್ಫಿಡೆನ್ಸ್',
    apiCalls: 'API ಕಾಲ್ಸ್', languageUsage: 'ಲ್ಯಾಂಗ್ವೇಜ್ ಯೂಸೇಜ್',
    confidenceTrend: 'ಕಾನ್ಫಿಡೆನ್ಸ್ ಟ್ರೆಂಡ್', dailyActivity: 'ಡೈಲಿ ಆಕ್ಟಿವಿಟಿ',
    thisWeek: 'ದಿಸ್ ವೀಕ್', connectedChannels: 'ಕನೆಕ್ಟೆಡ್ ಚಾನೆಲ್ಸ್',
    supportedLanguages: 'ಸಪೋರ್ಟೆಡ್ ಲ್ಯಾಂಗ್ವೇಜಸ್', visionTranslateTitle: 'ವಿಷನ್ ಟ್ರಾನ್ಸ್‌ಲೇಟ್',
    dropImageHere: 'ಇಮೇಜ್ ಡ್ರಾಪ್ ಮಾಡಿ', newImage: 'ನ್ಯೂ ಇಮೇಜ್',
    typeEnglishHere: 'ಇಲ್ಲಿ ಇಂಗ್ಲಿಷ್ ಟೈಪ್ ಮಾಡಿ…', translationAppears: 'ಟ್ರಾನ್ಸ್‌ಲೇಶನ್ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ',
    translationsNative: 'ಟ್ರಾನ್ಸ್‌ಲೇಶನ್ (ನೇಟಿವ್)', textTranslate: 'ಟೆಕ್ಸ್ಟ್ ಟ್ರಾನ್ಸ್‌ಲೇಟ್',
    original: 'ಒರಿಜಿನಲ್', copyAll: 'ಕಾಪಿ ಆಲ್', download: 'ಡೌನ್‌ಲೋಡ್',
    noResults: 'ರಿಸಲ್ಟ್ ಇಲ್ಲ', starred: 'ಸ್ಟಾರ್ಡ್',
    nativeToEnglishDesc: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮಾತಾಡಿ, ಇಂಗ್ಲಿಷ್ ಪಡೆಯಿರಿ',
    continuousListeningDesc: 'ಹ್ಯಾಂಡ್ಸ್-ಫ್ರೀ ವಿದ್ ಸೈಲೆನ್ಸ್ ಡಿಟೆಕ್ಷನ್',
    englishToNativeDesc: 'ಇಂಗ್ಲಿಷ್ ಟೈಪ್ ಮಾಡಿ, ನೇಟಿವ್ ಟ್ರಾನ್ಸ್‌ಲೇಶನ್ ಪಡೆಯಿರಿ',
    visionTranslateDesc: 'ಇಮೇಜ್‌ನಿಂದ ಟೆಕ್ಸ್ಟ್ ಟ್ರಾನ್ಸ್‌ಲೇಟ್ ಮಾಡಿ',
    chooseMode: 'ಪ್ರಾರಂಭಿಸಲು ಮೋಡ್ ಆಯ್ಕೆ ಮಾಡಿ',
    termsPreserved: 'ಟರ್ಮ್ಸ್ ಪ್ರಿಸರ್ವ್ಡ್',
    pressStartListening: 'ಸ್ಟಾರ್ಟ್ ಲಿಸನಿಂಗ್ ಪ್ರೆಸ್ ಮಾಡಿ',
    shortcuts: 'ಶಾರ್ಟ್‌ಕಟ್ಸ್',
    multiLangOutput: 'ಮಲ್ಟಿ-ಲ್ಯಾಂಗ್ವೇಜ್ ಔಟ್‌ಪುಟ್',
    rewriteTone: 'ರಿರೈಟ್ ಟೋನ್',
    dropAudioHere: 'ಆಡಿಯೋ ಫೈಲ್ ಡ್ರಾಪ್ ಮಾಡಿ',
    aiTools: 'AI ಟೂಲ್ಸ್',
    transcript: 'ಟ್ರಾನ್ಸ್‌ಕ್ರಿಪ್ಟ್',
    speechToText: 'ಸ್ಪೀಚ್ ಟು ಟೆಕ್ಸ್ಟ್',
    uploadAudio: 'ಅಪ್‌ಲೋಡ್ ಆಡಿಯೋ',
    transcribingAudio: 'ಟ್ರಾನ್ಸ್‌ಕ್ರೈಬಿಂಗ್ ಆಡಿಯೋ…',
    startListening: 'ಸ್ಟಾರ್ಟ್ ಲಿಸನಿಂಗ್',
    stopListening: 'ಸ್ಟಾಪ್ ಲಿಸನಿಂಗ್',
  },

  'ta-IN': {
    home: 'ஹோம்', translation: 'டிரான்ஸ்லேஷன்', nativeToEnglish: 'நேட்டிவ் டு இங்கிலீஷ்',
    continuousListening: 'கண்டினியஸ் லிஸனிங்', englishToNative: 'இங்கிலீஷ் டு நேட்டிவ்',
    visionTranslate: 'விஷன் டிரான்ஸ்லேட்', library: 'லைப்ரரி', history: 'ஹிஸ்டரி',
    profile: 'ப்ரொஃபைல்', settings: 'செட்டிங்ஸ்', logout: 'லாக்அவுட்',
    settingsTitle: 'செட்டிங்ஸ்', managePreferences: 'உங்கள் ப்ரெஃபரன்சஸ் மேனேஜ் செய்யுங்கள்',
    profileTitle: 'ப்ரொஃபைல்', accountPreferences: 'அக்கவுண்ட் & ப்ரெஃபரன்சஸ்',
    defaultLanguage: 'டிஃபால்ட் லாங்குவேஜ்', translate: 'டிரான்ஸ்லேட்', translating: 'டிரான்ஸ்லேட்டிங்…',
    transcriptHistory: 'டிரான்ஸ்கிரிப்ட் ஹிஸ்டரி', noHistory: 'ஹிஸ்டரி இல்லை',
    savedRewrites: 'சேவ்ட் ரிரைட்ஸ்',
    totalTranscripts: 'டோட்டல் டிரான்ஸ்கிரிப்ட்ஸ்', avgConfidence: 'ஆவரேஜ் கான்ஃபிடன்ஸ்',
    apiCalls: 'API கால்ஸ்', languageUsage: 'லாங்குவேஜ் யூசேஜ்',
    confidenceTrend: 'கான்ஃபிடன்ஸ் டிரெண்ட்', dailyActivity: 'டெய்லி ஆக்டிவிட்டி',
    thisWeek: 'திஸ் வீக்', connectedChannels: 'கனெக்டட் சேனல்ஸ்',
    supportedLanguages: 'சப்போர்ட்டட் லாங்குவேஜஸ்', visionTranslateTitle: 'விஷன் டிரான்ஸ்லேட்',
    dropImageHere: 'இமேஜ் டிராப் செய்யுங்கள்', newImage: 'நியூ இமேஜ்',
    typeEnglishHere: 'இங்கே இங்கிலீஷ் டைப் செய்யுங்கள்…', translationAppears: 'டிரான்ஸ்லேஷன் இங்கே தெரியும்',
    translationsNative: 'டிரான்ஸ்லேஷன் (நேட்டிவ்)', textTranslate: 'டெக்ஸ்ட் டிரான்ஸ்லேட்',
    original: 'ஒரிஜினல்', copyAll: 'காப்பி ஆல்', download: 'டவுன்லோட்',
    noResults: 'ரிசல்ட் இல்லை', starred: 'ஸ்டார்ட்',
    nativeToEnglishDesc: 'உங்கள் மொழியில் பேசுங்கள், இங்கிலீஷ் பெறுங்கள்',
    continuousListeningDesc: 'ஹேண்ட்ஸ்-ஃப்ரீ வித் சைலன்ஸ் டிடெக்ஷன்',
    englishToNativeDesc: 'இங்கிலீஷ் டைப் செய்யுங்கள், நேட்டிவ் டிரான்ஸ்லேஷன் பெறுங்கள்',
    visionTranslateDesc: 'இமேஜிலிருந்து டெக்ஸ்ட் டிரான்ஸ்லேட் செய்யுங்கள்',
    chooseMode: 'தொடங்க மோட் தேர்ந்தெடுங்கள்',
    termsPreserved: 'டர்ம்ஸ் ப்ரிசர்வ்ட்',
    pressStartListening: 'ஸ்டார்ட் லிஸனிங் பிரஸ் செய்யுங்கள்',
    shortcuts: 'ஷார்ட்கட்ஸ்',
    multiLangOutput: 'மல்டி-லாங்குவேஜ் அவுட்புட்',
    rewriteTone: 'ரிரைட் டோன்',
    dropAudioHere: 'ஆடியோ ஃபைல் டிராப் செய்யுங்கள்',
    aiTools: 'AI டூல்ஸ்',
    transcript: 'டிரான்ஸ்கிரிப்ட்',
    speechToText: 'ஸ்பீச் டு டெக்ஸ்ட்',
    uploadAudio: 'அப்லோட் ஆடியோ',
    transcribingAudio: 'டிரான்ஸ்கிரைபிங் ஆடியோ…',
    startListening: 'ஸ்டார்ட் லிஸனிங்',
    stopListening: 'ஸ்டாப் லிஸனிங்',
  },

  'te-IN': {
    home: 'హోమ్', translation: 'ట్రాన్స్‌లేషన్', nativeToEnglish: 'నేటివ్ టు ఇంగ్లీష్',
    continuousListening: 'కంటిన్యూయస్ లిజనింగ్', englishToNative: 'ఇంగ్లీష్ టు నేటివ్',
    visionTranslate: 'విజన్ ట్రాన్స్‌లేట్', library: 'లైబ్రరీ', history: 'హిస్టరీ',
    profile: 'ప్రొఫైల్', settings: 'సెట్టింగ్స్', logout: 'లాగ్‌అవుట్',
    settingsTitle: 'సెట్టింగ్స్', managePreferences: 'మీ ప్రెఫరెన్సెస్ మేనేజ్ చేయండి',
    profileTitle: 'ప్రొఫైల్', accountPreferences: 'అకౌంట్ & ప్రెఫరెన్సెస్',
    defaultLanguage: 'డిఫాల్ట్ లాంగ్వేజ్', translate: 'ట్రాన్స్‌లేట్', translating: 'ట్రాన్స్‌లేటింగ్…',
    transcriptHistory: 'ట్రాన్స్‌క్రిప్ట్ హిస్టరీ', noHistory: 'హిస్టరీ లేదు',
    savedRewrites: 'సేవ్డ్ రిరైట్స్',
    totalTranscripts: 'టోటల్ ట్రాన్స్‌క్రిప్ట్స్', avgConfidence: 'యావరేజ్ కాన్ఫిడెన్స్',
    apiCalls: 'API కాల్స్', languageUsage: 'లాంగ్వేజ్ యూసేజ్',
    confidenceTrend: 'కాన్ఫిడెన్స్ ట్రెండ్', dailyActivity: 'డైలీ యాక్టివిటీ',
    thisWeek: 'దిస్ వీక్', connectedChannels: 'కనెక్టెడ్ చానెల్స్',
    supportedLanguages: 'సపోర్టెడ్ లాంగ్వేజెస్', visionTranslateTitle: 'విజన్ ట్రాన్స్‌లేట్',
    dropImageHere: 'ఇమేజ్ డ్రాప్ చేయండి', newImage: 'న్యూ ఇమేజ్',
    typeEnglishHere: 'ఇక్కడ ఇంగ్లీష్ టైప్ చేయండి…', translationAppears: 'ట్రాన్స్‌లేషన్ ఇక్కడ కనిపిస్తుంది',
    translationsNative: 'ట్రాన్స్‌లేషన్ (నేటివ్)', textTranslate: 'టెక్స్ట్ ట్రాన్స్‌లేట్',
    original: 'ఒరిజినల్', copyAll: 'కాపీ ఆల్', download: 'డౌన్‌లోడ్',
    noResults: 'రిజల్ట్ లేదు', starred: 'స్టార్డ్',
    nativeToEnglishDesc: 'మీ భాషలో మాట్లాడండి, ఇంగ్లీష్ పొందండి',
    continuousListeningDesc: 'హ్యాండ్స్-ఫ్రీ విత్ సైలెన్స్ డిటెక్షన్',
    englishToNativeDesc: 'ఇంగ్లీష్ టైప్ చేయండి, నేటివ్ ట్రాన్స్‌లేషన్ పొందండి',
    visionTranslateDesc: 'ఇమేజ్ నుండి టెక్స్ట్ ట్రాన్స్‌లేట్ చేయండి',
    chooseMode: 'ప్రారంభించడానికి మోడ్ ఎంచుకోండి',
    termsPreserved: 'టర్మ్స్ ప్రిజర్వ్డ్',
    pressStartListening: 'స్టార్ట్ లిజనింగ్ ప్రెస్ చేయండి',
    shortcuts: 'షార్ట్‌కట్స్',
    multiLangOutput: 'మల్టీ-లాంగ్వేజ్ అవుట్‌పుట్',
    rewriteTone: 'రిరైట్ టోన్',
    dropAudioHere: 'ఆడియో ఫైల్ డ్రాప్ చేయండి',
    aiTools: 'AI టూల్స్',
    transcript: 'ట్రాన్స్‌క్రిప్ట్',
    speechToText: 'స్పీచ్ టు టెక్స్ట్',
    uploadAudio: 'అప్‌లోడ్ ఆడియో',
    transcribingAudio: 'ట్రాన్స్‌క్రైబింగ్ ఆడియో…',
    startListening: 'స్టార్ట్ లిజనింగ్',
    stopListening: 'స్టాప్ లిజనింగ్',
  },

  'bn-IN': {
    home: 'হোম', translation: 'ট্রান্সলেশন', nativeToEnglish: 'নেটিভ টু ইংলিশ',
    continuousListening: 'কন্টিনিউয়াস লিসেনিং', englishToNative: 'ইংলিশ টু নেটিভ',
    visionTranslate: 'ভিশন ট্রান্সলেট', library: 'লাইব্রেরি', history: 'হিস্ট্রি',
    profile: 'প্রোফাইল', settings: 'সেটিংস', logout: 'লগআউট',
    settingsTitle: 'সেটিংস', managePreferences: 'আপনার প্রেফারেন্সেস ম্যানেজ করুন',
    profileTitle: 'প্রোফাইল', accountPreferences: 'অ্যাকাউন্ট & প্রেফারেন্সেস',
    defaultLanguage: 'ডিফল্ট ল্যাঙ্গুয়েজ', translate: 'ট্রান্সলেট', translating: 'ট্রান্সলেটিং…',
    transcriptHistory: 'ট্রান্সক্রিপ্ট হিস্ট্রি', noHistory: 'হিস্ট্রি নেই',
    savedRewrites: 'সেভড রিরাইটস',
    totalTranscripts: 'টোটাল ট্রান্সক্রিপ্টস', avgConfidence: 'অ্যাভারেজ কনফিডেন্স',
    apiCalls: 'API কলস', languageUsage: 'ল্যাঙ্গুয়েজ ইউসেজ',
    confidenceTrend: 'কনফিডেন্স ট্রেন্ড', dailyActivity: 'ডেইলি অ্যাক্টিভিটি',
    thisWeek: 'দিস উইক', connectedChannels: 'কানেক্টেড চ্যানেলস',
    supportedLanguages: 'সাপোর্টেড ল্যাঙ্গুয়েজেস', visionTranslateTitle: 'ভিশন ট্রান্সলেট',
    dropImageHere: 'ইমেজ ড্রপ করুন', newImage: 'নিউ ইমেজ',
    typeEnglishHere: 'এখানে ইংলিশ টাইপ করুন…', translationAppears: 'ট্রান্সলেশন এখানে দেখাবে',
    translationsNative: 'ট্রান্সলেশন (নেটিভ)', textTranslate: 'টেক্সট ট্রান্সলেট',
    original: 'অরিজিনাল', copyAll: 'কপি অল', download: 'ডাউনলোড',
    noResults: 'রেজাল্ট নেই', starred: 'স্টার্ড',
    nativeToEnglishDesc: 'আপনার ভাষায় বলুন, ইংলিশ পান',
    continuousListeningDesc: 'হ্যান্ডস-ফ্রি উইথ সাইলেন্স ডিটেকশন',
    englishToNativeDesc: 'ইংলিশ টাইপ করুন, নেটিভ ট্রান্সলেশন পান',
    visionTranslateDesc: 'ইমেজ থেকে টেক্সট ট্রান্সলেট করুন',
    chooseMode: 'শুরু করতে মোড বেছে নিন',
    termsPreserved: 'টার্মস প্রিজার্ভড',
    pressStartListening: 'স্টার্ট লিসেনিং প্রেস করুন',
    shortcuts: 'শর্টকাটস',
    multiLangOutput: 'মাল্টি-ল্যাঙ্গুয়েজ আউটপুট',
    rewriteTone: 'রিরাইট টোন',
    dropAudioHere: 'অডিও ফাইল ড্রপ করুন',
    aiTools: 'AI টুলস',
    transcript: 'ট্রান্সক্রিপ্ট',
    speechToText: 'স্পিচ টু টেক্সট',
    uploadAudio: 'আপলোড অডিও',
    transcribingAudio: 'ট্রান্সক্রাইবিং অডিও…',
    startListening: 'স্টার্ট লিসেনিং',
    stopListening: 'স্টপ লিসেনিং',
  },

  'ml-IN': {
    home: 'ഹോം', translation: 'ട്രാൻസ്‌ലേഷൻ', nativeToEnglish: 'നേറ്റീവ് ടു ഇംഗ്ലീഷ്',
    continuousListening: 'കണ്ടിന്യൂഅസ് ലിസനിംഗ്', englishToNative: 'ഇംഗ്ലീഷ് ടു നേറ്റീവ്',
    visionTranslate: 'വിഷൻ ട്രാൻസ്‌ലേറ്റ്', library: 'ലൈബ്രറി', history: 'ഹിസ്റ്ററി',
    profile: 'പ്രൊഫൈൽ', settings: 'സെറ്റിംഗ്സ്', logout: 'ലോഗ്‌ഔട്ട്',
    settingsTitle: 'സെറ്റിംഗ്സ്', managePreferences: 'നിങ്ങളുടെ പ്രെഫറൻസസ് മാനേജ് ചെയ്യുക',
    profileTitle: 'പ്രൊഫൈൽ', accountPreferences: 'അക്കൗണ്ട് & പ്രെഫറൻസസ്',
    defaultLanguage: 'ഡിഫോൾട്ട് ലാംഗ്വേജ്', translate: 'ട്രാൻസ്‌ലേറ്റ്', translating: 'ട്രാൻസ്‌ലേറ്റിംഗ്…',
    transcriptHistory: 'ട്രാൻസ്‌ക്രിപ്റ്റ് ഹിസ്റ്ററി', noHistory: 'ഹിസ്റ്ററി ഇല്ല',
    savedRewrites: 'സേവ്ഡ് റിരൈറ്റ്സ്',
    totalTranscripts: 'ടോട്ടൽ ട്രാൻസ്‌ക്രിപ്റ്റ്സ്', avgConfidence: 'ആവറേജ് കോൺഫിഡൻസ്',
    apiCalls: 'API കോൾസ്', languageUsage: 'ലാംഗ്വേജ് യൂസേജ്',
    confidenceTrend: 'കോൺഫിഡൻസ് ട്രെൻഡ്', dailyActivity: 'ഡെയ്‌ലി ആക്ടിവിറ്റി',
    thisWeek: 'ദിസ് വീക്ക്', connectedChannels: 'കണക്ടഡ് ചാനൽസ്',
    supportedLanguages: 'സപ്പോർട്ടഡ് ലാംഗ്വേജസ്', visionTranslateTitle: 'വിഷൻ ട്രാൻസ്‌ലേറ്റ്',
    dropImageHere: 'ഇമേജ് ഡ്രോപ്പ് ചെയ്യുക', newImage: 'ന്യൂ ഇമേജ്',
    typeEnglishHere: 'ഇവിടെ ഇംഗ്ലീഷ് ടൈപ്പ് ചെയ്യുക…', translationAppears: 'ട്രാൻസ്‌ലേഷൻ ഇവിടെ കാണും',
    translationsNative: 'ട്രാൻസ്‌ലേഷൻ (നേറ്റീവ്)', textTranslate: 'ടെക്സ്റ്റ് ട്രാൻസ്‌ലേറ്റ്',
    original: 'ഒറിജിനൽ', copyAll: 'കോപ്പി ഓൾ', download: 'ഡൗൺലോഡ്',
    noResults: 'റിസൾട്ട് ഇല്ല', starred: 'സ്റ്റാർഡ്',
    nativeToEnglishDesc: 'നിങ്ങളുടെ ഭാഷയിൽ സംസാരിക്കുക, ഇംഗ്ലീഷ് നേടുക',
    continuousListeningDesc: 'ഹാൻഡ്സ്-ഫ്രീ വിത്ത് സൈലൻസ് ഡിറ്റക്ഷൻ',
    englishToNativeDesc: 'ഇംഗ്ലീഷ് ടൈപ്പ് ചെയ്യുക, നേറ്റീവ് ട്രാൻസ്‌ലേഷൻ നേടുക',
    visionTranslateDesc: 'ഇമേജിൽ നിന്ന് ടെക്സ്റ്റ് ട്രാൻസ്‌ലേറ്റ് ചെയ്യുക',
    chooseMode: 'ആരംഭിക്കാൻ മോഡ് തിരഞ്ഞെടുക്കുക',
    termsPreserved: 'ടേംസ് പ്രിസർവ്ഡ്',
    pressStartListening: 'സ്റ്റാർട്ട് ലിസനിംഗ് പ്രസ്സ് ചെയ്യുക',
    shortcuts: 'ഷോർട്ട്‌കട്ട്സ്',
    multiLangOutput: 'മൾട്ടി-ലാംഗ്വേജ് ഔട്ട്‌പുട്ട്',
    rewriteTone: 'റിരൈറ്റ് ടോൺ',
    dropAudioHere: 'ഓഡിയോ ഫയൽ ഡ്രോപ്പ് ചെയ്യുക',
    aiTools: 'AI ടൂൾസ്',
    transcript: 'ട്രാൻസ്‌ക്രിപ്റ്റ്',
    speechToText: 'സ്പീച്ച് ടു ടെക്സ്റ്റ്',
    uploadAudio: 'അപ്‌ലോഡ് ഓഡിയോ',
    transcribingAudio: 'ട്രാൻസ്‌ക്രൈബിംഗ് ഓഡിയോ…',
    startListening: 'സ്റ്റാർട്ട് ലിസനിംഗ്',
    stopListening: 'സ്റ്റോപ്പ് ലിസനിംഗ്',
  },

  'mr-IN': {
    home: 'होम', translation: 'ट्रान्सलेशन', nativeToEnglish: 'नेटिव्ह टू इंग्लिश',
    continuousListening: 'कंटिन्युअस लिसनिंग', englishToNative: 'इंग्लिश टू नेटिव्ह',
    visionTranslate: 'व्हिजन ट्रान्सलेट', library: 'लायब्ररी', history: 'हिस्ट्री',
    profile: 'प्रोफाइल', settings: 'सेटिंग्ज', logout: 'लॉगआउट',
    settingsTitle: 'सेटिंग्ज', managePreferences: 'तुमच्या प्रेफरन्सेस मॅनेज करा',
    profileTitle: 'प्रोफाइल', accountPreferences: 'अकाउंट & प्रेफरन्सेस',
    defaultLanguage: 'डिफॉल्ट लँग्वेज', translate: 'ट्रान्सलेट', translating: 'ट्रान्सलेटिंग…',
    transcriptHistory: 'ट्रान्सक्रिप्ट हिस्ट्री', noHistory: 'हिस्ट्री नाही',
    savedRewrites: 'सेव्ड रिराइट्स',
    totalTranscripts: 'टोटल ट्रान्सक्रिप्ट्स', avgConfidence: 'अॅव्हरेज कॉन्फिडन्स',
    apiCalls: 'API कॉल्स', languageUsage: 'लँग्वेज यूसेज',
    confidenceTrend: 'कॉन्फिडन्स ट्रेंड', dailyActivity: 'डेली अॅक्टिव्हिटी',
    thisWeek: 'दिस वीक', connectedChannels: 'कनेक्टेड चॅनेल्स',
    supportedLanguages: 'सपोर्टेड लँग्वेजेस', visionTranslateTitle: 'व्हिजन ट्रान्सलेट',
    dropImageHere: 'इमेज ड्रॉप करा', newImage: 'न्यू इमेज',
    typeEnglishHere: 'इथे इंग्लिश टाइप करा…', translationAppears: 'ट्रान्सलेशन इथे दिसेल',
    translationsNative: 'ट्रान्सलेशन (नेटिव्ह)', textTranslate: 'टेक्स्ट ट्रान्सलेट',
    original: 'ओरिजिनल', copyAll: 'कॉपी ऑल', download: 'डाउनलोड',
    noResults: 'रिझल्ट नाही', starred: 'स्टार्ड',
    nativeToEnglishDesc: 'तुमच्या भाषेत बोला, इंग्लिश मिळवा',
    continuousListeningDesc: 'हँड्स-फ्री विथ सायलन्स डिटेक्शन',
    englishToNativeDesc: 'इंग्लिश टाइप करा, नेटिव्ह ट्रान्सलेशन मिळवा',
    visionTranslateDesc: 'इमेजमधून टेक्स्ट ट्रान्सलेट करा',
    chooseMode: 'सुरू करण्यासाठी मोड निवडा',
    termsPreserved: 'टर्म्स प्रिझर्व्ड',
    pressStartListening: 'स्टार्ट लिसनिंग प्रेस करा',
    shortcuts: 'शॉर्टकट्स',
    multiLangOutput: 'मल्टी-लँग्वेज आउटपुट',
    rewriteTone: 'रिराइट टोन',
    dropAudioHere: 'ऑडिओ फाइल ड्रॉप करा',
    aiTools: 'AI टूल्स',
    transcript: 'ट्रान्सक्रिप्ट',
    speechToText: 'स्पीच टू टेक्स्ट',
    uploadAudio: 'अपलोड ऑडिओ',
    transcribingAudio: 'ट्रान्सक्राइबिंग ऑडिओ…',
    startListening: 'स्टार्ट लिसनिंग',
    stopListening: 'स्टॉप लिसनिंग',
  },

  'gu-IN': {
    home: 'હોમ', translation: 'ટ્રાન્સ્લેશન', nativeToEnglish: 'નેટિવ ટુ ઇંગ્લિશ',
    continuousListening: 'કન્ટિન્યુઅસ લિસનિંગ', englishToNative: 'ઇંગ્લિશ ટુ નેટિવ',
    visionTranslate: 'વિઝન ટ્રાન્સ્લેટ', library: 'લાઇબ્રેરી', history: 'હિસ્ટ્રી',
    profile: 'પ્રોફાઇલ', settings: 'સેટિંગ્સ', logout: 'લૉગઆઉટ',
    settingsTitle: 'સેટિંગ્સ', managePreferences: 'તમારી પ્રેફરન્સ મેનેજ કરો',
    profileTitle: 'પ્રોફાઇલ', accountPreferences: 'એકાઉન્ટ & પ્રેફરન્સ',
    defaultLanguage: 'ડિફૉલ્ટ લૅન્ગ્વેજ', translate: 'ટ્રાન્સ્લેટ', translating: 'ટ્રાન્સ્લેટિંગ…',
    transcriptHistory: 'ટ્રાન્સ્ક્રિપ્ટ હિસ્ટ્રી', noHistory: 'હિસ્ટ્રી નથી',
    savedRewrites: 'સેવ્ડ રિરાઇટ્સ',
    totalTranscripts: 'ટોટલ ટ્રાન્સ્ક્રિપ્ટ્સ', avgConfidence: 'એવરેજ કૉન્ફિડન્સ',
    apiCalls: 'API કૉલ્સ', languageUsage: 'લૅન્ગ્વેજ યૂઝેજ',
    confidenceTrend: 'કૉન્ફિડન્સ ટ્રેન્ડ', dailyActivity: 'ડેઇલી એક્ટિવિટી',
    thisWeek: 'ધિસ વીક', connectedChannels: 'કનેક્ટેડ ચૅનલ્સ',
    supportedLanguages: 'સપોર્ટેડ લૅન્ગ્વેજ', visionTranslateTitle: 'વિઝન ટ્રાન્સ્લેટ',
    dropImageHere: 'ઇમેજ ડ્રૉપ કરો', newImage: 'ન્યૂ ઇમેજ',
    typeEnglishHere: 'અહીં ઇંગ્લિશ ટાઇપ કરો…', translationAppears: 'ટ્રાન્સ્લેશન અહીં દેખાશે',
    translationsNative: 'ટ્રાન્સ્લેશન (નેટિવ)', textTranslate: 'ટેક્સ્ટ ટ્રાન્સ્લેટ',
    original: 'ઓરિજિનલ', copyAll: 'કૉપી ઑલ', download: 'ડાઉનલોડ',
    noResults: 'રિઝલ્ટ નથી', starred: 'સ્ટાર્ડ',
    nativeToEnglishDesc: 'તમારી ભાષામાં બોલો, ઇંગ્લિશ મેળવો',
    continuousListeningDesc: 'હૅન્ડ્સ-ફ્રી વિથ સાઇલન્સ ડિટેક્શન',
    englishToNativeDesc: 'ઇંગ્લિશ ટાઇપ કરો, નેટિવ ટ્રાન્સ્લેશન મેળવો',
    visionTranslateDesc: 'ઇમેજમાંથી ટેક્સ્ટ ટ્રાન્સ્લેટ કરો',
    chooseMode: 'શરૂ કરવા માટે મોડ પસંદ કરો',
    termsPreserved: 'ટર્મ્સ પ્રિઝર્વ્ડ',
    pressStartListening: 'સ્ટાર્ટ લિસનિંગ પ્રેસ કરો',
    shortcuts: 'શૉર્ટકટ્સ',
    multiLangOutput: 'મલ્ટી-લૅન્ગ્વેજ આઉટપુટ',
    rewriteTone: 'રિરાઇટ ટોન',
    dropAudioHere: 'ઑડિઓ ફાઇલ ડ્રૉપ કરો',
    aiTools: 'AI ટૂલ્સ',
    transcript: 'ટ્રાન્સ્ક્રિપ્ટ',
    speechToText: 'સ્પીચ ટૂ ટેક્સ્ટ',
    uploadAudio: 'અપલોડ ઑડિઓ',
    transcribingAudio: 'ટ્રાન્સ્ક્રાઇબિંગ ઑડિઓ…',
    startListening: 'સ્ટાર્ટ લિસનિંગ',
    stopListening: 'સ્ટૉપ લિસનિંગ',
  },

  'pa-IN': {
    home: 'ਹੋਮ', translation: 'ਟ੍ਰਾਂਸਲੇਸ਼ਨ', nativeToEnglish: 'ਨੇਟਿਵ ਟੂ ਇੰਗਲਿਸ਼',
    continuousListening: 'ਕੰਟੀਨਿਊਅਸ ਲਿਸਨਿੰਗ', englishToNative: 'ਇੰਗਲਿਸ਼ ਟੂ ਨੇਟਿਵ',
    visionTranslate: 'ਵਿਜ਼ਨ ਟ੍ਰਾਂਸਲੇਟ', library: 'ਲਾਇਬ੍ਰੇਰੀ', history: 'ਹਿਸਟਰੀ',
    profile: 'ਪ੍ਰੋਫਾਈਲ', settings: 'ਸੈਟਿੰਗਸ', logout: 'ਲੌਗਆਊਟ',
    settingsTitle: 'ਸੈਟਿੰਗਸ', managePreferences: 'ਆਪਣੀਆਂ ਪ੍ਰੈਫਰੈਂਸਸ ਮੈਨੇਜ ਕਰੋ',
    profileTitle: 'ਪ੍ਰੋਫਾਈਲ', accountPreferences: 'ਅਕਾਊਂਟ & ਪ੍ਰੈਫਰੈਂਸਸ',
    defaultLanguage: 'ਡਿਫਾਲਟ ਲੈਂਗੁਏਜ', translate: 'ਟ੍ਰਾਂਸਲੇਟ', translating: 'ਟ੍ਰਾਂਸਲੇਟਿੰਗ…',
    transcriptHistory: 'ਟ੍ਰਾਂਸਕ੍ਰਿਪਟ ਹਿਸਟਰੀ', noHistory: 'ਹਿਸਟਰੀ ਨਹੀਂ',
    savedRewrites: 'ਸੇਵਡ ਰਿਰਾਈਟਸ',
    totalTranscripts: 'ਟੋਟਲ ਟ੍ਰਾਂਸਕ੍ਰਿਪਟਸ', avgConfidence: 'ਐਵਰੇਜ ਕਾਨਫੀਡੈਂਸ',
    apiCalls: 'API ਕਾਲਸ', languageUsage: 'ਲੈਂਗੁਏਜ ਯੂਸੇਜ',
    confidenceTrend: 'ਕਾਨਫੀਡੈਂਸ ਟ੍ਰੈਂਡ', dailyActivity: 'ਡੇਲੀ ਐਕਟੀਵਿਟੀ',
    thisWeek: 'ਦਿਸ ਵੀਕ', connectedChannels: 'ਕਨੈਕਟਡ ਚੈਨਲਸ',
    supportedLanguages: 'ਸਪੋਰਟਡ ਲੈਂਗੁਏਜਸ', visionTranslateTitle: 'ਵਿਜ਼ਨ ਟ੍ਰਾਂਸਲੇਟ',
    dropImageHere: 'ਇਮੇਜ ਡ੍ਰੌਪ ਕਰੋ', newImage: 'ਨਿਊ ਇਮੇਜ',
    typeEnglishHere: 'ਇੱਥੇ ਇੰਗਲਿਸ਼ ਟਾਈਪ ਕਰੋ…', translationAppears: 'ਟ੍ਰਾਂਸਲੇਸ਼ਨ ਇੱਥੇ ਦਿਖੇਗਾ',
    translationsNative: 'ਟ੍ਰਾਂਸਲੇਸ਼ਨ (ਨੇਟਿਵ)', textTranslate: 'ਟੈਕਸਟ ਟ੍ਰਾਂਸਲੇਟ',
    original: 'ਓਰਿਜਿਨਲ', copyAll: 'ਕਾਪੀ ਆਲ', download: 'ਡਾਊਨਲੋਡ',
    noResults: 'ਰਿਜ਼ਲਟ ਨਹੀਂ', starred: 'ਸਟਾਰਡ',
    nativeToEnglishDesc: 'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਬੋਲੋ, ਇੰਗਲਿਸ਼ ਪਾਓ',
    continuousListeningDesc: 'ਹੈਂਡਸ-ਫ੍ਰੀ ਵਿਦ ਸਾਈਲੈਂਸ ਡਿਟੈਕਸ਼ਨ',
    englishToNativeDesc: 'ਇੰਗਲਿਸ਼ ਟਾਈਪ ਕਰੋ, ਨੇਟਿਵ ਟ੍ਰਾਂਸਲੇਸ਼ਨ ਪਾਓ',
    visionTranslateDesc: 'ਇਮੇਜ ਤੋਂ ਟੈਕਸਟ ਟ੍ਰਾਂਸਲੇਟ ਕਰੋ',
    chooseMode: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਮੋਡ ਚੁਣੋ',
    termsPreserved: 'ਟਰਮਸ ਪ੍ਰਿਜ਼ਰਵਡ',
    pressStartListening: 'ਸਟਾਰਟ ਲਿਸਨਿੰਗ ਪ੍ਰੈੱਸ ਕਰੋ',
    shortcuts: 'ਸ਼ਾਰਟਕੱਟਸ',
    multiLangOutput: 'ਮਲਟੀ-ਲੈਂਗੁਏਜ ਆਉਟਪੁੱਟ',
    rewriteTone: 'ਰਿਰਾਈਟ ਟੋਨ',
    dropAudioHere: 'ਆਡੀਓ ਫਾਈਲ ਡ੍ਰੌਪ ਕਰੋ',
    aiTools: 'AI ਟੂਲਸ',
    transcript: 'ਟ੍ਰਾਂਸਕ੍ਰਿਪਟ',
    speechToText: 'ਸਪੀਚ ਟੂ ਟੈਕਸਟ',
    uploadAudio: 'ਅਪਲੋਡ ਆਡੀਓ',
    transcribingAudio: 'ਟ੍ਰਾਂਸਕ੍ਰਾਈਬਿੰਗ ਆਡੀਓ…',
    startListening: 'ਸਟਾਰਟ ਲਿਸਨਿੰਗ',
    stopListening: 'ਸਟੌਪ ਲਿਸਨਿੰਗ',
  },

  'or-IN': {
    home: 'ହୋମ', translation: 'ଟ୍ରାନ୍ସଲେସନ', nativeToEnglish: 'ନେଟିଭ ଟୁ ଇଂଲିଶ',
    continuousListening: 'କଣ୍ଟିନ୍ୟୁଅସ ଲିସନିଂ', englishToNative: 'ଇଂଲିଶ ଟୁ ନେଟିଭ',
    visionTranslate: 'ଭିଜନ ଟ୍ରାନ୍ସଲେଟ', library: 'ଲାଇବ୍ରେରୀ', history: 'ହିଷ୍ଟ୍ରି',
    profile: 'ପ୍ରୋଫାଇଲ', settings: 'ସେଟିଂସ', logout: 'ଲଗଆଉଟ',
    settingsTitle: 'ସେଟିଂସ', managePreferences: 'ଆପଣଙ୍କ ପ୍ରେଫରେନ୍ସ ମ୍ୟାନେଜ କରନ୍ତୁ',
    profileTitle: 'ପ୍ରୋଫାଇଲ', accountPreferences: 'ଆକାଉଣ୍ଟ & ପ୍ରେଫରେନ୍ସ',
    defaultLanguage: 'ଡିଫଲ୍ଟ ଲ୍ୟାଙ୍ଗୁଏଜ', translate: 'ଟ୍ରାନ୍ସଲେଟ', translating: 'ଟ୍ରାନ୍ସଲେଟିଂ…',
    transcriptHistory: 'ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ ହିଷ୍ଟ୍ରି', noHistory: 'ହିଷ୍ଟ୍ରି ନାହିଁ',
    savedRewrites: 'ସେଭ୍ଡ ରିରାଇଟ୍ସ',
    totalTranscripts: 'ଟୋଟାଲ ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ୍ସ', avgConfidence: 'ଆଭରେଜ କନ୍‌ଫିଡେନ୍ସ',
    apiCalls: 'API କଲ୍ସ', languageUsage: 'ଲ୍ୟାଙ୍ଗୁଏଜ ୟୁସେଜ',
    confidenceTrend: 'କନ୍‌ଫିଡେନ୍ସ ଟ୍ରେଣ୍ଡ', dailyActivity: 'ଡେଲି ଆକ୍ଟିଭିଟି',
    thisWeek: 'ଦିସ ୱିକ', connectedChannels: 'କନେକ୍ଟଡ ଚ୍ୟାନେଲ୍ସ',
    supportedLanguages: 'ସପୋର୍ଟଡ ଲ୍ୟାଙ୍ଗୁଏଜ', visionTranslateTitle: 'ଭିଜନ ଟ୍ରାନ୍ସଲେଟ',
    dropImageHere: 'ଇମେଜ ଡ୍ରପ କରନ୍ତୁ', newImage: 'ନ୍ୟୁ ଇମେଜ',
    typeEnglishHere: 'ଏଠାରେ ଇଂଲିଶ ଟାଇପ କରନ୍ତୁ…', translationAppears: 'ଟ୍ରାନ୍ସଲେସନ ଏଠାରେ ଦେଖାଯିବ',
    translationsNative: 'ଟ୍ରାନ୍ସଲେସନ (ନେଟିଭ)', textTranslate: 'ଟେକ୍ସଟ ଟ୍ରାନ୍ସଲେଟ',
    original: 'ଓରିଜିନାଲ', copyAll: 'କପି ଅଲ', download: 'ଡାଉନଲୋଡ',
    noResults: 'ରିଜଲ୍ଟ ନାହିଁ', starred: 'ଷ୍ଟାର୍ଡ',
    nativeToEnglishDesc: 'ଆପଣଙ୍କ ଭାଷାରେ କୁହନ୍ତୁ, ଇଂଲିଶ ପାଆନ୍ତୁ',
    continuousListeningDesc: 'ହ୍ୟାଣ୍ଡ୍ସ-ଫ୍ରି ୱିଦ ସାଇଲେନ୍ସ ଡିଟେକ୍ସନ',
    englishToNativeDesc: 'ଇଂଲିଶ ଟାଇପ କରନ୍ତୁ, ନେଟିଭ ଟ୍ରାନ୍ସଲେସନ ପାଆନ୍ତୁ',
    visionTranslateDesc: 'ଇମେଜରୁ ଟେକ୍ସଟ ଟ୍ରାନ୍ସଲେଟ କରନ୍ତୁ',
    chooseMode: 'ଆରମ୍ଭ କରିବାକୁ ମୋଡ ବାଛନ୍ତୁ',
    termsPreserved: 'ଟର୍ମ୍ସ ପ୍ରିଜର୍ଭ୍ଡ',
    pressStartListening: 'ଷ୍ଟାର୍ଟ ଲିସନିଂ ପ୍ରେସ କରନ୍ତୁ',
    shortcuts: 'ଶର୍ଟକଟ୍ସ',
    multiLangOutput: 'ମଲ୍ଟି-ଲ୍ୟାଙ୍ଗୁଏଜ ଆଉଟ୍‌ପୁଟ',
    rewriteTone: 'ରିରାଇଟ ଟୋନ',
    dropAudioHere: 'ଅଡିଓ ଫାଇଲ ଡ୍ରପ କରନ୍ତୁ',
    aiTools: 'AI ଟୁଲ୍ସ',
    transcript: 'ଟ୍ରାନ୍ସକ୍ରିପ୍ଟ',
    speechToText: 'ସ୍ପୀଚ ଟୁ ଟେକ୍ସଟ',
    uploadAudio: 'ଅପଲୋଡ ଅଡିଓ',
    transcribingAudio: 'ଟ୍ରାନ୍ସକ୍ରାଇବିଂ ଅଡିଓ…',
    startListening: 'ଷ୍ଟାର୍ଟ ଲିସନିଂ',
    stopListening: 'ଷ୍ଟପ ଲିସନିଂ',
  },
};

export function getLabels(langCode) {
  return LABELS[langCode] || LABELS['en'];
}
